services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    image: bigo-guessr

    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - SKIP_DATABASE_CHECK=true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:1777/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  default:
    name: nginx-network
    external: true
